CREATE TABLE mood_entries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  mood VARCHAR(255) NOT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user_id INT,
  FOREIGN KEY (user_id) REFERENCES users(id)
);