version: '3.8'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wellness_sync
    ports:
      - "3306:3306"
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db